all:
  vars:
    ansible_user: uap
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    tailscale_manage: true
  children:
    linux_nodes:
      children:
        k3s_servers:
        k3s_agents:
    k3s_servers:
      hosts:
        uap-home-1:
          ansible_host: 192.168.0.201
          k3s_node_name: uap-home-1
          k3s_cluster_init: true
          tailnet_ip: 100.106.223.120
          tailnet_name: uap-home-1.tail9fd337.ts.net
          min_memory_mb: 2048
          min_cpu_count: 1
        uap-home-2:
          ansible_host: 192.168.0.202
          k3s_node_name: uap-home-2
          tailnet_ip: 100.94.228.67
          tailnet_name: uap-home-2.tail9fd337.ts.net
          min_memory_mb: 2048
          min_cpu_count: 1
        uap-vps-1:
          ansible_host: REPLACE_WITH_PUBLIC_OR_LAN_IP
          k3s_node_name: uap-vps-1
          tailnet_ip: REPLACE_WITH_TAILNET_IP
          tailnet_name: uap-vps-1.tail9fd337.ts.net
          min_memory_mb: 1024
          min_cpu_count: 1
    k3s_agents:
      hosts: {}
