#!/usr/bin/env python3
"""Render the pinned mission overlay into the production ConfigMap."""

from __future__ import annotations

import argparse
import pathlib


ROOT = pathlib.Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "clusters/prod/infra/hermes-mission-runtime.yaml"
SOURCES = ("apply_overlay.py", "runtime.py", "local_stt.py")


def render() -> str:
    lines = [
        "# Generated by tools/hermes-mission/render_configmap.py; do not edit by hand.",
        "apiVersion: v1",
        "kind: ConfigMap",
        "metadata:",
        "  name: hermes-mission-runtime",
        "  namespace: uap-system",
        "data:",
    ]
    source_root = pathlib.Path(__file__).resolve().parent
    for name in SOURCES:
        lines.append(f"  {name}: |")
        text = (source_root / name).read_text(encoding="utf-8")
        lines.extend(f"    {line}" if line else "" for line in text.splitlines())
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=pathlib.Path, default=OUTPUT)
    args = parser.parse_args()
    expected = render()
    output = args.output.resolve()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"mission-configmap-drift: run {__file__}")
    else:
        output.write_text(expected, encoding="utf-8", newline="\n")
    print("hermes-mission-configmap-ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
