apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-api
    namespace: uap-system
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:Sufn66DyVpPYMHHJBj5EneJ/he9ZNOLWEbd5qs7LCp0BFOOVTe7Pqm6A8/E3x6KgdrXQJ/CEiyEScTpRhKNDQg==,iv:/w2nncgnF4+GCQVnkqLI6bC02YNudGbxtAFYwHb25CY=,tag:pvtzG+GPuM9qGIRCqub7tw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZmRjWndQMnovT3VLVC9v
            eUVOVUc2RTk4bXBNZklZT2NWdStpTzVIMW5rCmk5Q1ZWYnI3aE94eXRFWG5oSkJq
            QWV5eXZOV1JiSzljMnlpT21OS0VSU0EKLS0tIEVTVDRzczRiK2o2T252U3U4MGZD
            SGxvaHQ0YkxSVEQ2MzlQS0ZpejdGVDQKoDuQt+MA1Ocu1JtHz9xg9LgrVWFEOaqu
            +vZj/9yLVY6AcuLPWCrmHzczCF2AembljIo+v2UYvYeEidesSJCqZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ellxh9rynjv2n2sau9mekpt3qmt7r9w7t7zqjj6plx3nd2d0cg9sys9s85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T07:33:38Z"
    mac: ENC[AES256_GCM,data:cMfsn3D/mayEwnUQqQNmhW1bYOT5/xxiKyeZ3rHWwdsskutsl4ss9f6FnNsz1Q1iYmBuw7XR0bzYkyYY0cQ/nUfrWfDTkafhHl7sL5n+bImhB/e14fzf1L4BBC+pfStDi+2M7smvNlPT1/8HwsGiibdM8naan0gRbXmjlX6lzR4=,iv:BzZ1sbYTqU8rw4/h9HEBn1txThN5Rip9ayzPlnLEAxo=,tag:wOIKDq3ATGR3VroE2WfFmw==,type:str]
    version: 3.13.1
