apiVersion: v1
kind: Secret
metadata:
    name: hermes-keys
    namespace: uap-system
type: Opaque
stringData:
    LITELLM_KEY: ENC[AES256_GCM,data:D7fciq/+Cy0khzbg1V+bQp+tfEN+1DZ5P1B3xQOFznVwCt+6FBvQ3HBrbQ==,iv:QF8H/ncr17ccTvc3Ox3tXosbsb5WhKRnNAvtIj1GF9s=,tag:Lm62rqFdUOSj4Z5YhhuRCQ==,type:str]
    HERMES_KEY: ENC[AES256_GCM,data:HfNwn4eogj3Mn2ppw3MpdKopEIqkpAKwBkYqIER1jn+97bowdsKiDam1lIc8jvYtqDkykH/2SA==,iv:wnh9ZcrHe5cothEXQvBSN6XxzDV69cGbRHvEgsTj9ic=,tag:bB1nAOGvZ9czYF3CQvqpSg==,type:str]
    HERMES_KEYS_JSON: ENC[AES256_GCM,data:HcyhiPYPNuH0SWiazM5FzY2+XIZGMAw/D+k/o36WEdPUzPIegQIZlYzz6XT8F+ek5VodvkVZTLomiQ5hN2JELIUbDw==,iv:EUTP38aSslUD6ZQG7lU+x6BJUXiaewkMvO19RgbJxXw=,tag:oSgA6a5pTt79EYhcPwCLzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaUlUZy82K1pSSU9CRnJV
            aHdqdFRqdEIzQ1B4Q1R4MkF5OGRTelZBbVc0CncwYU9YRkN2N1c3RjZ4UU85OEN2
            KzRvNVBlRGVhNmpnbU9jSkhMNXlSNFEKLS0tIHNBNkpUWHNBU1dvZndUZnJkay9k
            dGFaYjltc1VLQ1owT2N3cjdweksvRlkKdWauQ5Tj0dcH51igCcnuCW8F48qUsrOS
            nD1UKJhRb+n1UO2l3NiOC1iKb9ZEv+dp3sZadahFY90v/p62SKc4qQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ellxh9rynjv2n2sau9mekpt3qmt7r9w7t7zqjj6plx3nd2d0cg9sys9s85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T08:31:03Z"
    mac: ENC[AES256_GCM,data:uHoA+jmKRMujISB6WGcCCSPuAcAXiZuKpx9RuUekdrBooZGwvpiDP8kmw9nkvrdHwb+9iO3fVONjJcqLjdz9bZJIV5DzdCwtb+Cg7gcs1+DEUoA2RNTeoptE1yRX5CodnZMhR378F6Dxq9kF5SH38ZNyOKSB+JAyM+OtrI/wGDE=,iv:lhtw8APDk8TeXuaJFognaZXJkbpB42JK6+l1mNwbnfA=,tag:9QDjLWJPnnq7dRRV3zdpyw==,type:str]
    version: 3.13.1
