apiVersion: v1
kind: Secret
metadata:
    name: hermes-keys
    namespace: uap-system
type: Opaque
stringData:
    LITELLM_KEY: ENC[AES256_GCM,data:XTeRtIxhf1khhE3s0WD5wDP7bytjRNa7vrxMgPpKaBIN5+PNDNdqYPFhfw==,iv:xQR9WF0DEK8mflQJQANylZzm7pUH8NQPngGu2Feyaa8=,tag:Z7GsjaDLXCwyVOfh09CTAA==,type:str]
    HERMES_KEY: ENC[AES256_GCM,data:T9FM/hQnrA+q1ca/O6fR/B0SyAzoYFjRHbOzmLrEU5xZ9/ePacb9yOiuuuYJApEPk3WPJUfgEw==,iv:gqmXNE1RlJavAMI5bowQfO4QLeEHCU+fT+3hiw54KGs=,tag:1ElDmpAv4+3yymWItpIH8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxa2tSVVRQeEZiRllwQitS
            eDlPR0gzekk3dXAxUjhzdno3UTRBQklEOHhzCnBEZ0sxOUtPM3NhNk9USVpBWXE2
            WkRyM09NdnhtR2NXcHBQYTZ1c2F5LzgKLS0tIGJab1E2ODNCa1BaTWNtNk02aDh1
            cGFDano5dVdCY25zd3IybGdqNTlyajQKH9miYrAgAz8sqpKZjb7CuCr1OcdU17BE
            ux5uXB2IroepLbGrLtSjc3rOTaeZQxxVh9tkeNubrbi81Sbl+IUn+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ellxh9rynjv2n2sau9mekpt3qmt7r9w7t7zqjj6plx3nd2d0cg9sys9s85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T22:12:14Z"
    mac: ENC[AES256_GCM,data:B0CStPcPcWcYKgoo0+lMmcwS9declUG9+oUxm2VNq3gxK+YEGFNdjkLLIY5qrmlSZssBVzfFJWsp0LUPJ4IYuN+kn/r9sxK7oJ4yjED9mPpTK83ebnWlE/fgdXa56wfA58H2kptvTA8Xdy0/yVuOuY4idruc+29J2skCMpUwomA=,iv:WLJpDvycDLEfsOhJFhpphHmrkoUEzljIJ0fkJN8pF3s=,tag:QniL3HjWhXeVNq0mBNfDIw==,type:str]
    version: 3.13.1
