apiVersion: v1
data:
    oauth-token: ENC[AES256_GCM,data:h2++ahKvbtLXCKlylitgGnqzMiPbgnYEl9CX3SsVlMhZNf+Exs79z9YL6uHhdYPrbdDYW3Kgs5CGQ5zZ021wnzfbGfroqc6khsS0yYVGbRrnnzpbnAzltSW40uf3ogapXTEIYbAuNq9BczOv2y528Y6Owz5M3FfLr9H8kkjcdznvPbFaSKAGPnPczMoH6aaY,iv:eRRiWvChes798iLfC3Sa9BELZodDCdJdhIKHSxPNxhc=,tag:EAUtCT75lNWc05ljKWJIUA==,type:str]
kind: Secret
metadata:
    name: hermes-agent-claude
    namespace: uap-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYWJERzhSdmc4K0VSN3BW
            MEhsMGpNOXdDNnBRNjNqUytoL083S0dwbVhNClF0U1hhRE0wcnVIOVV4SmNaejRs
            K1lsRC95U29hd2ZjNElsUzFyTEhab1UKLS0tIHFyVlRWbGlrazBpTUxYRTdZbEZm
            VlVZKzdqUnJoZmNxY09QRXVuWSt0VFkKiTbu6kCvYKh4I3298WV5zhJXZxGtc/aB
            qSslKinjCnZx4Qoy1jvpRonS/Z3iDFXSv2hLkbK7nLDlOY4gav9cOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ellxh9rynjv2n2sau9mekpt3qmt7r9w7t7zqjj6plx3nd2d0cg9sys9s85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T20:17:55Z"
    mac: ENC[AES256_GCM,data:WWvUdcx484E89jgvrI91cTJiChhbB6FTxpLn7EX3QO+uE1N5jVPGLXaIjLOrqPyZFI35iyCLpDntK21NZ4umLG6KTy6sfHMI3Ozg+eTlDTEsfMHnaeDZQ8E1GEYdVeepWH4JL/Iy5bUdwi7lKsV2p3Q/a1U1S085XmkLWabszzI=,iv:ZALX+ykCjj70U+mRPBMvQj9GvVZs+By26N0kin0Wtjk=,tag:Xz6dRcZ0uaJcpB358Sg9cA==,type:str]
    version: 3.13.1
