apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-api
    namespace: uap-system
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:v1SpAoE2+fy7OwGMhym0oTmLepp2su6ScnyQu2hDJNst52XlOP4p7vGLKnlmns4WltPF/x52Jc+I1wUy4uMPEQ==,iv:GSTs1L0cepD2nHdRV9SMuKikcrzoMgJszxhylVgPmLo=,tag:Lr3Tw8fahmK24T4WIIDOMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVlJ1SUNZV2FRaWdkR1dY
            UUZRaE9QYTdUd2tqbjBZMTBkSmh1bWIrU1ZnCkh6SXByUUdGWU1xQ0NKaTJGUTho
            anRkMGo5SEZNYzN5bUdCbXREMjdjYVEKLS0tIFZhZ3lSa1ZVMStBWnJzL3BrUUVW
            YVRMRkM2ZTdRRG5aY1NHT0hEb01qZVEK8XdFDcixd29Rj+LVBhgKAJbJB6ByZ/kl
            Q192SwGL2sQrGzC1WyE3MIu70LcTCqtumcZzVijp+rJu0g+onnFg+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ellxh9rynjv2n2sau9mekpt3qmt7r9w7t7zqjj6plx3nd2d0cg9sys9s85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T11:01:52Z"
    mac: ENC[AES256_GCM,data:My9dBLITxGjZE4lYhvVH+AIvcPezN1zgyubP7yfHEKQimIiFKh2fs4MZkUcufuush/I2rXxLvrpKHUlRXVEOOVqm5SElrkN0JYGljRBRkQrMuwZ+UtW2g2BPvHsVC3b8kpkJ3x4uJS+n1jDyIlN7UzlC4t3NwRuNbmu87vO6vko=,iv:bL8avDuUU84B0C/Qoh/qq12aBQVe+K+MXGyFNILB4Fg=,tag:6KmxeahtDwHZq9yyOu2GeQ==,type:str]
    version: 3.13.0
