apiVersion: v1
kind: Secret
metadata:
    name: singbox-egress-config
    namespace: uap-system
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:tX8rf3BOrG7DwYlDOxx9XsA3pJPRp7BiAo3gczfNHoeO/4Ad3pXze6Lj6IBg+oqm6dbA2qOhAwQqoJm+YJ6f9VT3HqoLmU/FavELLT6phGHMv7sYiveYIzaAn59cGUf3E6e10rZaJtakqrPYPzgc9LOcPJtav7orx5sX7lvipJsf7eHQFZP3x/5bDTv4RiLQJkpCJBVRugKYJZsnBHUqIl5r2P9qdNRxArVsJ5xtjkZ5RusTtah3YjcCQHwg7qIRKRSmoGeRsCL5+ireikqoJ+ToNKYENZZ+jqHCWq+74++gjiQdvPge3xL/rhKl9vJF3sMh+zhJs1rjb2/oWcpmiBbjR1Q8eVigD+/Ovcb16Q4u0yqZQgoYdzAnz8tNnmvq/2en7SAv+6AxHa7IU74bIVwfYbhG313BgGawucqeBo5oSCLyJC8IyqsHWJy/ymTJcKE3MA66/5KGX24lTS/eBV/PJPEWkSRW6Z7NPfq93Ys8eUj3rtFRgILccOisboQmKK1TqVNfr2qQsr50zl8L9/dhepdUMBoW56XjMPlaj1OP9LtMVcfFHF6E3DFItg5gGuTaxVC7j/sv9HRHA3hPEoJifIjM3IlnPSWybLDwPwvVfzg0VV9BjzHhz4Egmd113Eo+c5hwm2iWsvqSfxGkuVMCIqqJzReSI0qsa/FaSIRnvzJqKKcF1zYVNFEdAj4HQFE5dbaJjUJr1ilgE77dbd8doVmDdsLwKGZEWXfXyu9PiWOFiq3neqJZ18kcQ0uYA6w+UfWLTt/4Zp+MWGveVOVbPE9N9hWS6ZgES3Cj8dZFwloYFNLUmAQGcIRfNf5+UKlfOFXFMWcPjO6cshWQrAFyyCbkiOigm/UmFCHTWeo1KUxEtnLNXUPyusPaM3KwuMBxzArsENN9FS3ERv4a0LPZJVjnm7cynLKfP40S0TiVXHup6qubv8CrLJ1szO1pQC/IU4FD8PMyXN1jXtOIeN3gWfvWC8DeLh0pTLYCcVrz9AMF2ZYvxcG+QhHcw0uL8jnhO5bXqGORCeWL4/dOoYs/i99ArnrhjUBk36RcmfDnkhuEWmx6LFVOgivjPDapotijuVR0Ouws/iJOnuoq3Ll4NVK5MASlrxJB7qAEvi8O1ExhbcgajPRdr1n3G3b3Ca4kkjj2w13fnWyl4U5wSytI3Bz4u2OYS0hNm4/DGwZo8Q==,iv:urnMavhDMPr0+p5lHJBTYsFq1qU5a3ltgrexGFl8BkU=,tag:zWxFVQ+mRwafs78sAkgsog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZnJRWlVkRDd1Z2dwdDdi
            ek1xN2dLZjl3T01DL0huUmZxOHltWlRlWUFFClVKZ3JKNit5ajV5WjNqaDgwYWJ1
            bktDbDZZQ1lWZk1Zam94bTZCcUFCdE0KLS0tIGROQ1lBOGdESEhVejVWUEZjSG5Q
            RXk2Rm9VZnZMUkdNeUdhLytaZnIwaGcKkTZHuwvwGA+jeeuaB6rhRNQFFZeFRHqP
            q9K5sRcfwPwmxEN07vV0XuDmQle0x8lwGpx3U9fYVHiWlLus3Uxnlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ellxh9rynjv2n2sau9mekpt3qmt7r9w7t7zqjj6plx3nd2d0cg9sys9s85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T09:26:51Z"
    mac: ENC[AES256_GCM,data:6p3pucb6p5pK/dN08nilG0uxVSK8y4tHN6Pab0gYFnDc9JeiyB7DHK5K+UWhpCFzN9hsRLuPRUncjNYnU3tGGwiorrMGM7SaZkQQ7uCOOUGoK+aCsgDZsodKnddaC5/6RA4CHNDMWfyiEsgzByWw0bdR0DQgP9nV6bOWm3TArNk=,iv:wWdT/c3MmRt4HLLig3WHBC3XLihbegvIKooYuhsprLU=,tag:sDTNe//dhoTJyibLOxmmAA==,type:str]
    version: 3.13.1
