apiVersion: v1
kind: Secret
metadata:
    name: singbox-egress-config
    namespace: uap-system
type: Opaque
data:
    config.json: ENC[AES256_GCM,data:EicWphQHMc56bP2Zft/yGK4FsdTULzGUhSnrIh3G2vFU/oTH5vETMSdO8b6qGzf6FjFt6LpR+FMPQEc0JXRIHhDbHTMMcREPK+OZcMhp7nFY7fM+VHXpIvY/cwR8WqI7q2XEs0c8NC+diKLT+utXkXyFkOf0rFTVBjwgL83xAKHMZmMf0l1GhdvF+zpIvRu3nuM07bbxSvCJ2n44i7Owt3XC/mGBe1jpHtQ53yEsm4nW6BgEmjHacJhnT2T0NNONZfoy+3fwCikIMdf5YBWnR2n7RG99tTSNfTUILxgAZqrSEEAMIhpVjk1hyoRqaqeLZ9SGMHx8bypuTJKES0KNd7aYvR5NjzNVbcKxbgfioJDvWZB3M/Ttgmwzi2Ba0INXLfGvyNVeSUiivCiYgg8LLJr0cuRkvEUYny+r7AAE45xYcjjr0AVBqTVq7FVJkpXquK19LAsRZeEPV2Ymfxe2GQyo5F4TQMkkmKjJZDs872LBngdcJ/jL3KsA2cjsr9NEHCV+ZuOvpsITnGXQiHQafQ+juDCg0ykvAcyiO7+db77HIK9ooBD06/P3p0iFlO6FnAizHpYVl9feTXzIGOW94M4BauSA63OQb9GkOG4OKMGnu5NdpMejoBFspuzTHvSFTtqkvBd6HCpbzHdLVbGNNXVOyfRAk80d/VlQ74Y5cM7AddBHz4JAkNlkkPazxwdBTnIIPVcuY/NhaYA7+8D0IcRSlQlTvp6VWpHnJuvaT2Moa1J8i2A4xZW1HwwCJPuQQ9GXZ01+Wh0ymeGP24aWVbcUeYKN8aFCT1/InOdCOOC3HDCWE5fqV0gkFLn3Sz/d2HkbTom/iXuCTAo3gb5mJ/iwxMehfH1ehkJ0NWqv6nAU3QC+KuvoH+anhz/nfNQ4zbwUMGmJYcWSFhstV2rVGDnO4CEFMcNJJFAFMzGLa22MxSZX+FnUuTP86nmPBYDtHvxoMLWpUzigMah3uXbsybZpTOpOSa0VyeSamLUvB15mYnzGzOoXoqIl/yysD9agisytOE/gP4L1vkC7c+NIPJknkKtfz9g7sV3Gm+6wpVPkAf7We/V/GL+aMoA1O8rRlIxLo5TqeAd7a6oKNKaotwaKBnWuBlhAphF0JDhj1hyLx9qJFCFkXCAMY5hRflSGUnaezkI7OFBrMyc4c3P1pdW0sSbkfxkXcM0dKAVvKuoM8vrp3w3u+FNXj1P/aOtthgKzbN7C8bQ1A7GVOdJzjwSZ51TnDEMeHO1NcGhbrSbOp+m8a8VWw7vGbz09Jt0t41Q+H0FQgcry8sEZXqmlywhUC/6GdiD9tLFWVxCr8x+B/jnGJ6c5NQt9iRQ=,iv:cAYVMM8WmkiMFQokToHYIcBHJy4k2SrDu9bW4N6B88E=,tag:3iJYx4pjXM/a0YJUmTJSvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVlEzNE82OFl5RGRPTmRF
            MDQ1YytmbzFpM0xsem5SZTE4QWhVcGs4R1ZjCk5vdE5jMTdqekxDZmh3aW9sNGM2
            UThBK1FSMk1SeWkxOUJBOFVpSlIzdTgKLS0tIHFKeVpld1BRUGdVV3Rxc0tKMEFF
            K2NPdmJ4a01MUWd3RkYxdmxhSmdEd3MKintdWy01yM8FwBcjatxSPtLYh+LlvBmu
            ygzio2OM8hLS4rNIPPfdedxofeCg9CCDGcHs3OmgDqp/MDI0gy2LkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ellxh9rynjv2n2sau9mekpt3qmt7r9w7t7zqjj6plx3nd2d0cg9sys9s85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T19:42:58Z"
    mac: ENC[AES256_GCM,data:ehPiHXWPV2M4CdD8D3Ja3y4hZnOSM7/yR2o1hzcFi7PeFGLW5vWALZzD9D+yax57/Tul5zBvTpsmk3XQY/aexopAqMwP+W6w+SVccJXF8uEWQY/FEU7ExM2W+hVXf37fpk39+KMt0UFUIJMTjNiVRss9bg5EIr2xDQSHoDKzrJs=,iv:nK93zKI9ILWOu59Y5JdkS7WC/Fqmr+dhhNcRPJMg+cw=,tag:CVSGuJdSOS5DnQEQTyk/Zw==,type:str]
    version: 3.13.1
