apiVersion: v1
kind: Secret
metadata:
    name: singbox-egress-config
    namespace: uap-system
type: Opaque
data:
    config.json: ENC[AES256_GCM,data:agFF+HCwwNZFy1JBtEaly4AwHxbkRRXPkGBagD7LPsIcW2asU6rXTrA/HQ63E+oDc2V5k4/pr/YMNBFamzFwCHxDsLS4qA95SGbNHMiIkQrWf/RU0Ctcncevt/17O2rPDrtp1XaIoTkMHInQ0BD1TnpOjwa2ve51lBQqvIak2I34z3nBT0jVyWe8pNw5eBXVq3+Je9K0udaqSGKASxVfVBjgpl2F/9/FNn9+z2tV37Xiqle7lPbzuLB9PmNvz+AxIWvPmftrdaN+dOgA3bmuK4OCH0N75k7EFUCtlA6HEwQ0Ew2FGGCU+8LZ97qIHdNsr0AlO735tuBuWPUM2mMsQnqPBjRQrtn6wa2E8lr7LMkXPCYcfs6ZFNuaqUk9abmdnRY7jEbZYhggXQ70UpKTCx9U9ybz5RoxzUGYpCY3CLob0owZPbpYKPL+DmtASUG30+lSqcoZQ/aul5o992sFT/Iad+/36BdqwfPtA8iYJBhiQnbpgMuo8ACBgm42o5+5AGhapnYQ4ouRH2GMPun8f+1XIFOCNuhFw9xehaFgnQJMPKnE1vSuq4FqzENeB1Anz+r08rCuF2J3TuqLa0EJ4TgVrsCvagO83qkZyN2rSg7bR6GlS2cxpwQGFpyCTnHaLPmMGk8q7F5qdbiWNqJnR/S6J3W9KjWkFBcXUG+Uoda2TCUILA+wf95J7ch7NZEPSa8z40WCGZB+Sr2uH1KwqJczVufqDpRRpU1+TvK60wAGBA7eiLjQ5oF2xDXlVPkfU+Eo34AHhmDRQWWbtZN9KSR08gNwOC/eBoXj8W9cWMbBVtVYzeK0iVtEkdSgWGMjWCT8GxjanZxvK0pU82yJc+cYy6mQnKUCJA7CfzKo9opOVlzPc6onPyWb6aKXc+6lZlpOuYvpaW2DpgMSX4hhzmeuEYE2JfXtPkJjjsHWOqTu7ixf5y3F6+IwakK+UD9Ra1CuHfiSlLcC6Nu2yBmnKNKqJaGaI9h4NOIUJV91vXpEJRETU8QQU0js/MWKPBt3tTyZglTs4aw/N5CpvMmhC1OIc0jJClhlBT5aolI2jICi32MhGt/xDaVx93DClv7u2y53PWOiR5L2tnev0Z6SM49gEDwx+tHikmp2vgBSgnwOmZ/wra0p+NLQkfJPon0OqmEN6dIEuUqlJIRsvHDOvmrrz4X6jBSatqjdhZ3TaP8E9/LJUDi1pwh3lEKKZ3sD7ZyBwvODG/cA2oKd5NCH/a9tQ7cwwFeRD/RgAcIbttC8UkJVnS9gHDc7gOjMWYBcgpHmUz16YN2SWtYeM6XRWt/87AwKvImYcedAyPrjWigLflvRVB8w5Jh0sjQ=,iv:zzh+d+GWQDsO+vRY6O0d3aErT1uAaz0E3A6a/GgUDvQ=,tag:3MvFZjo48lZ7Iu8AY4CeHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSVN4YzhKMVdHSS9iWlNl
            ZjhXWEhUb0xNaTA5MnF4ZE1PcGthVTl0eVJZCjhpbFdadUhua0R5cE9qc2NrNG9t
            YVBWeExEM0puR2pTbEZNTnJUcDJ4UU0KLS0tIExWaUM2VHNoMWVOZ0h3MTdRbm9x
            Z2FWanhxbUUwNlBhcXkvazJkR0ZKZDAKioxwQNviHVLUnsR0+xuwsOwv4HPZqnxz
            xiHt6vWx7bBghYXajz3TU0rBAQHzT0Pv+k1AREOzGqA7MyU7NZQ9CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ellxh9rynjv2n2sau9mekpt3qmt7r9w7t7zqjj6plx3nd2d0cg9sys9s85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T23:36:31Z"
    mac: ENC[AES256_GCM,data:07QEEXffXd3cTigquRZzaMrC0Dj/9qhuDxbp8wNLnwFXcHigb2fiJiZcQzW9oe5+Y32dlk2bn+vGLi9e/a8lFPrJgnfIN56oBi1ntZdTQkNS8NevF1nOffsdJN8ydTE+6MRTXkQDWfd/UwVqV6v8cEO3UgT/2z4rEx20NAE0ZeY=,iv:sPWd29H89yStBY3aB2Dh/yEx1PGlz6E+31CM9bMwC6Y=,tag:cfC29nTEl8gm4eASedDatA==,type:str]
    version: 3.13.1
