apiVersion: v1
kind: Secret
metadata:
    name: subfleet-secrets
    namespace: uap-system
type: Opaque
stringData:
    bridgeSecret: ENC[AES256_GCM,data:l2IvTlLcMggu7Ob8yIKHNT1CMBmfXSdtr3Fu5t+TtN0iqf/7WuGm49AErJlL2z1s,iv:a6J2iA0Faj07JrW1d346uVZLWnY7xbA/T9qqIc83lNA=,tag:oWk5aEEZOSV6EW/1UfuUvg==,type:str]
    adminToken: ENC[AES256_GCM,data:PKvZtd5Y6zUDz7vjMVUtmzRvohY4DpNlp8VgGfxoSrAOr8lAL7duLl1BU18irHsu,iv:HxCBYb+s9/2IxL9dr/65um2ssT0x1vyl2PbHMONLsTQ=,tag:6c/h5UfalM/MUCd5+NuqLA==,type:str]
    credentials.json: ENC[AES256_GCM,data:5YdDIOQhavmpoQU1E1mGgxZzMsvnfQat/bXxJAfTeiEEbxh+JdTKfTNpK6ciiJHZikkXmt8XyT5VJeNMrKPfRMbB1PZGYjqjd6UBVnrgwgGUyGcCAJ3a0pK4xgYeLLeAo8wobQIJv6ccZZaIuJN84EqsWJIOK0jaIzbWfUxqpXjHk1m7EyAI0LN2GZgtwrLnf8N7Ok8Z9ctsqiOfGogjJvGTfN+jWyvW+XdkdKmEIbetfoI8Moy+pJqkve9i7WOf+MGgV/sgJf6gQAJhARwNzqInDLPQC1iVEsno7wqfzljQRCE2EEi2RV2nwyYEGtxtqgDH2hCXYUKgglSotv7I5gx75AjFPJAoa5njB7OHHTEnrjNDcNw2SmgszICOCx4FL9cu3iGonCAanpZuTIBiCE/Ymu8UT2PsTWUTpiN7Mwyf9g==,iv:TYb/jhcWpcfBTg2SwCmy+LNKk0xwHuir00QonXAuxV0=,tag:BQVLVT+8XiHfoB8jyZmPhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdUJRYTdZczRUbEhSWm04
            Ym1sTW43VFl3dFVUc084cFV2Yy9uTFNFUWlzCnlrM1hxYktwbURkM21oWVBKTnFm
            N1lPZEEzRnpwUVRHNWVzTmRCeFZWRmMKLS0tIDk3SklJVHBLTVFFakdROXdadlRu
            blB6M0tuZFpwK2ZlL2pGcWVhZExHNTAKslCuilYcxHyV2U6auI5RYOudEUzmGc8c
            hjgPTTbiOtQQfmdJq7n5CvW+vO76lSB3y3OPKRZpbnBva0OeA1CGdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ellxh9rynjv2n2sau9mekpt3qmt7r9w7t7zqjj6plx3nd2d0cg9sys9s85
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T09:25:43Z"
    mac: ENC[AES256_GCM,data:sQ/OVy7iUrlTzEbYnDyHJiKuFzFzoNeD11HLAmafVdwMb/bBnjFGlQryMMJgAzPJeYAlUUhY/1tnjz3iKyG+HLYp9jl+yKnUCqK2hf4+SoB4u/OPGDeQEBvVvrF4O3uDcRSBNDVB0HFnWfcl85VhfPw7M02VArMqNaXrpxtP/uY=,iv:1/PAlRLNXiJriLPnWiB89Vb37te6pZOGqPRWOe7u8Q4=,tag:yWgEXdLxp8WrkdS5zLT5zQ==,type:str]
    version: 3.13.1
